<footer id="page-footer" class="bg-body-light">
    <div class="content py-3">
        <div class="row fs-sm">
            <div class="col-sm-6 order-sm-2 py-1 text-center text-sm-end">
                Desarrollado <i class="fa fa-heart text-danger"></i> por <a class="fw-semibold" href="#" target="_blank">RiaCAD Systems</a>
            </div>
            <div class="col-sm-6 order-sm-1 py-1 text-center text-sm-start">Core KumbiaPHP
                <a class="fw-semibold" href="https://kumbiaphp.com" target="_blank"> <?= KUMBIA_VERSION ?></a> &copy; <span data-toggle="year-copy"></span>
            </div>
        </div>
    </div>
</footer>
