<?php CoreuiMenu::load(Menu::BACKEND, Session::get('perfil_id'));
?>
<!--
        Agregar la clase smini-hide a un elemento lo hará invisible (opacidad: 0) cuando la barra lateral esté en modo mini

        Agregar la clase smini-show a un elemento lo hará visible (opacidad: 1) cuando la barra lateral esté en modo mini

        Si deseas deshabilitar la animación de transición, asegúrate de agregar también la clase no-transition a tu elemento

        Agregar la clase smini-hidden a un elemento lo ocultará cuando la barra lateral esté en modo mini

        Agregar la clase smini-visible a un elemento lo mostrará (display: inline-block) solo cuando la barra lateral esté en modo mini

        Agregar la clase smini-visible-block a un elemento lo mostrará (display: block) solo cuando la barra lateral esté en modo mini
-->

<nav id="sidebar" aria-label="Main Navigation">
    <!-- Side Header -->
    <div class="content-header">
        <!-- Logo -->
        <a class="fw-semibold text-dual" href="/dashboard">
            <span class="smini-visible">
                <i class="fa fa-circle-notch text-primary"></i>
            </span>
            <span class="smini-hide fs-4 tracking-wider">DBKM<span class="fw-normal"><small> 2026</small></span></span>
        </a>
        <!-- END Logo -->

        <!-- Extra -->
        <div>
            <!-- Dark Mode -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
            <button type="button" class="btn btn-sm btn-alt-secondary" data-toggle="layout" data-action="dark_mode_toggle">
                <i class="far fa-moon"></i>
            </button>
            <!-- END Dark Mode -->

            <!-- END Options -->

            <!-- Close Sidebar, Visible only on mobile screens -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
            <a class="d-lg-none btn btn-sm btn-alt-secondary ms-1" data-toggle="layout" data-action="sidebar_close" href="javascript:void(0)">
                <i class="fa fa-fw fa-times"></i>
            </a>
            <!-- END Close Sidebar -->
        </div>
        <!-- END Extra -->
    </div>
    <!-- END Side Header -->

    <!-- Sidebar Scrolling -->
    <div class="js-sidebar-scroll">
        <!-- Side Navigation -->
        <div class="content-side">
            <?php CoreuiMenu::Desktop()
            ?>
        </div>
        <!-- END Side Navigation -->
    </div>
    <!-- END Sidebar Scrolling -->
</nav>
