<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-content">
                    <?php echo DwForm::openAjax(); ?>

                    <div class="row">
                        <div class="col-md-6">
                            <?php echo DwForm::text('producto.codigo', ['class' => 'input-required'], NULL, 'Código'); ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo DwForm::text('producto.nombre', ['class' => 'input-required'], NULL, 'Nombre'); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <?php echo DwForm::dbSelect('producto.categoria_id', 'nombre', array('administracion/categoria', 'find'), 'Seleccione...', array('class' => 'input-required'), NULL, 'Categoría'); ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo DwForm::dbSelect('producto.unidad_id', 'nombre', array('administracion/unidad', 'find'), 'Seleccione...', array('class' => 'input-required'), NULL, 'Unidad'); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <?php echo DwForm::number('producto.existencia', ['class' => 'input-required'], 0, 'Existencia'); ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo DwForm::number('producto.costo', ['class' => 'input-required'], 0.00, 'Costo'); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <?php echo DwForm::textarea('producto.descripcion', [], NULL, 'Descripción'); ?>
                        </div>
                    </div>

                    <div class="row mb-3 mt-3">
                        <div class="form-actions">
                            <div class="text-left">
                                <?php echo DwForm::send("Guardar"); ?>
                                <?php echo DwForm::cancel(); ?>
                            </div>
                        </div>
                    </div>
                    <?php echo DwForm::close(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->