<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-content">
                    <fieldset class="border p-2">
                        <legend class="float-none w-auto block-header block-header-default">Datos del producto</legend>
                        <div class="row text-center">
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Código:</label>
                                <h5><?= $producto->codigo ?? ''; ?></h5>
                            </div>
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Nombre:</label>
                                <h5><?= $producto->nombre ?? ''; ?></h5>
                            </div>
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Categoría:</label>
                                <h5><?= $producto->categoria_id ?? ''; ?></h5>
                            </div>
                        </div>
                        <div class="row text-center mt-3">
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Unidad:</label>
                                <h5><?= $producto->unidad_id ?? ''; ?></h5>
                            </div>
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Existencia:</label>
                                <h5><?= $producto->existencia ?? ''; ?></h5>
                            </div>
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Costo:</label>
                                <h5><?= $producto->costo ?? ''; ?></h5>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12">
                                <label for="" class="control-label mb-2">Descripción:</label>
                                <p><?= $producto->descripcion ?? ''; ?></p>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="block-content">
                    <div class="row mb-3 mt-3">
                        <div class="form-actions">
                            <div class="text-left">
                                <?= DwButton::back('administracion/productos/listar', 'Regresar al listado', 'fa-undo', 'Atras'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->