<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-content">

                    <?php echo DwForm::open(); ?>

                    <div class="row">
                        <div class="col-md-3 mb-3">
                            <?php echo Form::label('Fecha', 'Día', ['class' => 'form-label']); ?>
                            <?php echo Form::date('corte', ['class' => 'input-required input-date form-control', 'max' => date('Y-m-d')], date("Y-m-d"), 'Día'); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="form-actions">
                            <?php echo DwForm::send('Listar auditorías', 'fa-check-square-o', NULL, 'buscar'); ?>
                            <?php echo DwForm::focus('corte'); ?>
                        </div>
                    </div>

                    <?php echo DwForm::close(); ?>
                </div>
