<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">

  <title>KumbiaPHP</title>

  <meta name="description" content="KumbiaPHP - Bootstrap 5 OneUI Admin Template ">
  <meta name="robots" content="noindex, nofollow">

  <!-- Icons -->
  <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
  <link rel="shortcut icon" href="<?= PUBLIC_PATH ?>template/coreui/assets/media/favicons/favicon.png">
  <link rel="icon" type="image/png" sizes="192x192" href="<?= PUBLIC_PATH ?>template/coreui/assets/media/favicons/favicon-192x192.png">
  <link rel="apple-touch-icon" sizes="180x180" href="<?= PUBLIC_PATH ?>template/coreui/assets/media/favicons/apple-touch-icon-180x180.png">
  <!-- END Icons -->

  <!-- Stylesheets -->
  <!-- OneUI framework -->
  <link rel="stylesheet" id="css-main" href="<?= PUBLIC_PATH ?>template/coreui/assets/css/oneui.min.css">

  <!-- JQuery and OneUI PRECARGA -->
  <script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/lib/jquery.min.js"></script>
  <script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/oneui.app.min.js"></script>

  <!-- You can include a specific file from css/themes/ folder to alter the default color theme of the template. eg: -->
  <!-- <link rel="stylesheet" id="css-theme" href="<?= PUBLIC_PATH ?>template/coreui/assets/css/themes/amethyst.min.css"> -->
  <!-- END Stylesheets -->
</head>

<body>
  <!-- Page Container -->
  <!--
        Available classes for #page-container:

    GENERIC

      'remember-theme'                            Remembers active color theme and dark mode between pages using localStorage when set through
                                                  - Theme helper buttons [data-toggle="theme"],
                                                  - Layout helper buttons [data-toggle="layout" data-action="dark_mode_[on/off/toggle]"]
                                                  - ..and/or One.layout('dark_mode_[on/off/toggle]')

    SIDEBAR & SIDE OVERLAY

      'sidebar-r'                                 Right Sidebar and left Side Overlay (default is left Sidebar and right Side Overlay)
      'sidebar-mini'                              Mini hoverable Sidebar (screen width > 991px)
      'sidebar-o'                                 Visible Sidebar by default (screen width > 991px)
      'sidebar-o-xs'                              Visible Sidebar by default (screen width < 992px)
      'sidebar-dark'                              Dark themed sidebar

      'side-overlay-hover'                        Hoverable Side Overlay (screen width > 991px)
      'side-overlay-o'                            Visible Side Overlay by default

      'enable-page-overlay'                       Enables a visible clickable Page Overlay (closes Side Overlay on click) when Side Overlay opens

      'side-scroll'                               Enables custom scrolling on Sidebar and Side Overlay instead of native scrolling (screen width > 991px)

    HEADER

      ''                                          Static Header if no class is added
      'page-header-fixed'                         Fixed Header

    HEADER STYLE

      ''                                          Light themed Header
      'page-header-dark'                          Dark themed Header

    MAIN CONTENT LAYOUT

      ''                                          Full width Main Content if no class is added
      'main-content-boxed'                        Full width Main Content with a specific maximum width (screen width > 1200px)
      'main-content-narrow'                       Full width Main Content with a percentage width (screen width > 1200px)

    DARK MODE

      'sidebar-dark page-header-dark dark-mode'   Enable dark mode (light sidebar/header is not supported with dark mode)
    -->
  <div id="page-container" class="sidebar-o sidebar-dark enable-page-overlay side-scroll page-header-fixed">
    <!-- Side Overlay-->
    <?php View::partial('templates/coreui/aside') ?>
    <!-- END Side Overlay -->

    <!-- Sidebar -->
    <?php View::partial('templates/coreui/sidebar') ?>
    <!-- END Sidebar -->

    <!-- Header -->
    <?php View::partial('templates/coreui/header') ?>
    <!-- END Header -->

    <!-- Main Container -->
    <main id="main-container">
      <?php View::content() ?>
    </main>
    <!-- END Main Container -->

    <!-- Footer -->
    <?php View::partial('templates/coreui/footer') ?>
    <!-- END Footer -->
  </div>
  <!-- END Page Container -->

  <!--
        OneUI JS

        Core libraries and functionality
        webpack is putting everything together at <?= PUBLIC_PATH ?>template/coreui/assets/_js/main/app.js
    -->

  <!-- jQuery (required for Bootstrap's JavaScript plugins) -->

  <!-- Page JS Plugins -->
  <!-- <script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/chart.js/chart.min.js"></script> -->

  <!-- Page JS Code -->
  <script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/pages/be_pages_dashboard.min.js"></script>

  <!-- Ocultar las notificaciones -->

  <!-- CODIGO PARA CERRAR SESION -->
  <script type="text/javascript">
    var autoLogoutTimer;
    resetTimer();
    $(document).on('mouseover mousedown touchstart click keydown mousewheel DDMouseScroll wheel scroll', document, function(e) {
      //console.log(e.type); // Descomentar esta linea para revisar cuales eventos ocurren
      resetTimer();
    }); // resetTimer es usado para el conteo del tiempo para el logout
    function resetTimer() {
      clearTimeout(autoLogoutTimer)
      autoLogoutTimer = setTimeout(idleLogout, 300000) // 1000 = 1 segundo (tiempo de inactividad)
    }
    // idleLogout es usado redirigir al logout cuando se acaba el tiempo
    function idleLogout() {

      window.location.href = "<?php echo PUBLIC_PATH; ?>logout"; // redireccion para hacer logout
    }
  </script>
</body>

</html>
