<footer id="page-footer" class="bg-body-light">
    <div class="content py-3">
        <div class="row fs-sm">
            <div class="col-sm-4 order-sm-1 py-1 text-center text-sm-start">
                Desarrollado <i class="fa fa-heart text-danger"></i> por <a class="fw-semibold" href="#" target="_blank">RJR Sistemas</a> &copy; <?= date('Y') ?>
            </div>
            <div class="col-sm-4 order-sm-2 py-1 text-center">
                Core KumbiaPHP <a class="fw-semibold" href="https://kumbiaphp.com" target="_blank">1.2.0</a>
            </div>
            <div class="col-sm-4 order-sm-3 py-1 text-center text-sm-end">
                Versión del PHP <strong><?= PHP_VERSION ?></strong>
            </div>
        </div>
    </div>
</footer>
