<?php

return [
    'application' => [
        'name' => 'DBKM 2026',
        'base_url' => 'https://kumbiaphp.atumedida-hosting.com/',
        'production' => 'Off',
        'database' => 'development',
        'dbdate' => 'YYYY-MM-DD',
        'debug' => 'On',
        'log_exceptions' => 'On',
        'cache_driver' => 'file',
        'metadata_lifetime' => '+1 year',
        'namespace_auth' => 'default',
        'routes' => 'On',
        'template' => 'coreui',
    ],
    'custom' => [
        'app_mayus' => 'On',
        'app_update' => 'Off',
        'app_update_time' => '5 min',
        'app_version' => 2,
        'app_logger' => 'On',
        'app_local' => 'On',
        'app_ajax' => 'On',
        'app_lock_time' => 3,
        'app_session_timeout' => 5,
        'datagrid' => 20,
        'login_exclusion' => 'root, admin',
        'type_reports' => 'html.printer',
        'timezone' => 'America/Caracas',
        'empresa' => array (
  'nombre' => 'RRsistemas',
  'rif' => 'J-12345678-0',
  'direccion' => 'Urbanizacion colinas de Betania',
  'telefono' => '04129236406',
  'email' => 'robertjota@gmail.com',
  'web' => '',
),
    ],
];
