<?php View::flash(); ?>
<?php SectionManager::start('styles')  ?>
<!-- DataTables CSS -->
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-bs5/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-bs5/css/buttons.bootstrap5.min.css">
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive-bs5/css/responsive.bootstrap5.min.css">
<!-- END DataTables CSS -->
<?php SectionManager::end('styles')  ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header text-end">
                    <?= DwHtml::button("sistema/backups/crear/", 'Nuevo', null, 'fa-check')  ?>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="tBackups" class=" table table-bordered table-vcenter table-hover js-dataTable-full table-striped table-condensed table-responsive">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">FECHA</th>
                                    <th class="text-center">HORA</th>
                                    <th class="text-center">NOMBRE</th>
                                    <th class="text-center">CREADA POR</th>
                                    <th class="text-center">TAMAÑO</th>
                                    <th class="text-center">ARCHIVO</th>
                                    <th class="text-center">ACCIONES</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($backups->items as $backup): ?>
                                    <?php $key_res = Security::setKey($backup->id, 'restaurar_backup'); ?>
                                    <?php $key_dwn = Security::setKey($backup->id, 'descargar_backup'); ?>

                                    <tr data-backup-description="<?= $backup->denominacion; ?>" data-backup-file="<?= $backup->archivo; ?>" data-backup-datetime="<?= $backup->backup_at; ?>">
                                        <td class="text-center"><?= $backups->counter; ?></td>
                                        <td class="text-center"><?= date("Y-m-d", strtotime($backup->backup_at)); ?></td>
                                        <td class="text-center"><?= date("H:i:s", strtotime($backup->backup_at)); ?></td>
                                        <td><?= $backup->denominacion; ?></td>
                                        <td><?= $backup->nombre . ' ' . $backup->apellido; ?></td>
                                        <td><?= $backup->tamano; ?></td>
                                        <td><?= $backup->archivo; ?></td>
                                        <td class="text-center" nowrap width="15%">
                                            <?= DwHtml::buttonTable('Descargar backup', "sistema/backups/descargar/$key_dwn/", array('class' => 'no-ajax', 'target' => '_blank'), 'info', 'fa-download'); ?>
                                            <?= DwHtml::buttonTableSA('Restarurar sistema', "#", array('class' => 'js-confirm', 'data-to' => PUBLIC_PATH . "sistema/backups/restaurar/$key_res/", 'msg-title' => 'Restaurar sistema', 'msg' => 'Está seguro de querer restaurar el sistema con esta copia de seguridad?', 'on-confirm' => 'backupRestore'), 'danger', 'fa-warning'); ?>
                                        </td>
                                    </tr>
                                    <?php $backups->counter++; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->

<?php SectionManager::start('scripts')  ?>
<!-- DataTables JS Plugins -->
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-bs5/js/dataTables.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive-bs5/js/responsive.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/dataTables.buttons.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-bs5/js/buttons.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-jszip/jszip.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-pdfmake/pdfmake.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-pdfmake/vfs_fonts.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/buttons.print.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/buttons.html5.min.js"></script>

<!-- DataTables JS Code -->
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/_js/pages/be_tables_datatables.js"></script>

<?php SectionManager::end('scripts')  ?>
