<footer class="navbar navbar-inverse navbar-fixed-bottom hidden-xs">
    <div class="container">
        <div class="pull-right hidden-xs">
            <p>PHP: <?php echo phpversion(); ?> - APP: <?php echo KUMBIA_VERSION ?></p>
        </div>
        <div>
            <p class="visible-xs">&copy; Copyright <?php echo date("Y"); ?>.</p>
            <p class="visible-xs">Todos los derechos reservados.</p>
            <p class="hidden-xs">&copy; Copyright <?php echo date("Y"); ?>, <b>RJR Sistemas</b> - Core KumbiaPHP 1.2.0</p>
        </div>
    </div>
</footer>
