<?php View::flash(); ?>

<div class="content">
    <div class="card block-rounded shadow">
        <div class="card-header text-end">
            <?= DwHtml::button("sistema/usuarios/editar/" . Security::setKey($usuario->id, 'upd_usuario'), 'Editar', array('class' => 'btn-info'), 'fa-pencil'); ?>
            <?= DwHtml::button("sistema/usuarios/accesos/" . Security::setKey($usuario->id, 'shw_accesos'), 'Accesos', array('class' => 'btn-info'), 'fa-exchange'); ?>
        </div>
        <div class="card-body ">
            <?php echo DwForm::open(); ?>

            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo DwForm::text('usuario.nombre', array('class' => ' input-readonly'), $usuario->nombre, 'Nombre'); ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo DwForm::text('usuario.apellido', array('class' => ' input-readonly'), $usuario->apellido, 'Apellido'); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo DwForm::email('usuario.email', array('class' => ' input-readonly'), $usuario->email, 'Email'); ?>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 text-center hidden-xs hidden-sm">
                    <div class="shadow-dark" style="margin-top: 5px">
                        <?php echo DwHtml::img("upload/personas/$usuario->fotografia", $usuario->nombre . ' ' . $usuario->apellido, array('id' => 'img-persona')); ?>
                    </div>
                </div>
            </div>

            <?php echo DwForm::close(); ?>

            <hr />

            <div class="container-overflow">

                <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th>NUM</th>
                            <th>FECHA</th>
                            <th>IP</th>
                            <th>TIPO</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($accesos->items) { ?>
                            <?php foreach ($accesos->items as $acceso): ?>
                                <tr>
                                    <td><?php echo $accesos->counter; ?></td>
                                    <td><?php echo date("Y-m-d", strtotime($acceso->acceso_at)); ?></td>
                                    <td><?php echo date("H:i:s", strtotime($acceso->acceso_at)); ?></td>
                                    <td><?php echo $acceso->ip; ?></td>
                                    <td><?php echo ($acceso->tipo_acceso == Acceso::ENTRADA) ? '<span class="label label-success">Entrada</span>' : '<span class="label label-danger">Salida</span>';; ?></td>
                                </tr>
                                <?php $accesos->counter++; ?>
                            <?php endforeach; ?>
                        <?php } ?>
                    </tbody>
                </table>


            </div>

            <div class="row">
                <div class="form-actions">
                    <div class="text-left">
                        <?php echo DwButton::back(); ?>
                    </div>
                </div>
            </div>

        </div>
