<?php View::flash(); ?>
<div class="content">
    <div class="card block-rounded shadow">
        <div class="card-body">
            <?php echo DwForm::open(); ?>
            <div class="row">
                <div class="col-md-12">
                    <?php echo DwForm::textarea('estado_usuario.descripcion', array('class' => 'input-required mask-text'), NULL, 'Motivo del cambio de estado'); ?>
                </div>
            </div>
            <hr>
            <div class="col-md-12 text-end">
                <?php echo DwForm::send('Actualizar estado'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('estado_usuario.descripcion'); ?>
            </div>
            <?php echo DwForm::close(); ?>
        </div>
    </div>
