<?php View::flash(); ?>
<!-- DataTables CSS -->
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-bs5/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-bs5/css/buttons.bootstrap5.min.css">
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive-bs5/css/responsive.bootstrap5.min.css">
<!-- END DataTables CSS -->

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-header pt-3">
                    <h3 class="block-title"></h3>
                    <div class="block-options">
                        <?php echo DwHtml::button("sistema/usuarios/agregar/", 'Nuevo', NULL, 'fa-check-square'); ?>
                    </div>
                </div>
                <div class="block-content">
                    <div class="table-responsive mb-3">
                        <table id="tUsuarios" class="table table-bordered table-vcenter table-hover js-dataTable-buttons table-striped table-condensed table-responsive">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">USUARIO</th>
                                    <th class="text-center">NOMBRE</th>
                                    <th class="text-center">EMAIL</th>
                                    <th class="text-center">PERFIL</th>
                                    <th class="text-center">ESTADO</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $counter = 1; ?>
                                <?php foreach ($usuarios ?? [] as $usuario) : ?>
                                    <?php $key_shw = Security::setKey($usuario->id, 'shw_usuario'); ?>
                                    <?php $key_upd = Security::setKey($usuario->id, 'upd_usuario'); ?>
                                    <?php $key_ina = Security::setKey($usuario->id, 'bloquear_usuario'); ?>
                                    <?php $key_rea = Security::setKey($usuario->id, 'reactivar_usuario'); ?>
                                    <tr>
                                        <td><?php echo $counter; ?></td>
                                        <td><?php echo $usuario->login; ?></td>
                                        <td><?php echo $usuario->nombre . ' ' . $usuario->apellido; ?></td>
                                        <td><?php echo $usuario->email; ?></td>
                                        <td><?php echo $usuario->perfil; ?></td>
                                        <td class="text-center"><button class="status-toggle"
                                                data-user-id="<?php echo $usuario->id; ?>"
                                                data-status="<?php echo $usuario->estado_usuario; ?>"
                                                data-key="<?php echo Security::setKey($usuario->id, 'change_status'); ?>">
                                                <?= ($usuario->estado_usuario == EstadoUsuario::ACTIVO) ?
                                                    '<span class="badge bg-success">Activo</span>' :
                                                    '<span class="badge bg-danger">Bloqueado</span>'; ?>
                                            </button></td>
                                        <td class="text-center" width="10%" nowrap>

                                            <?php echo DwHtml::buttonTable('Editar usuario', "sistema/usuarios/editar/$key_upd/", NULL, 'outline-warning', 'fa-pencil'); ?>
                                            <?php if ($usuario->estado_usuario == EstadoUsuario::ACTIVO) { ?>
                                                <?php echo DwHtml::buttonTable('Bloquear usuario', "sistema/usuarios/estado/bloquear/$key_ina/", NULL, 'outline-success', 'fa-flag'); ?>
                                            <?php } else { ?>
                                                <?php echo DwHtml::buttonTable('Reactivar usuario', "sistema/usuarios/estado/reactivar/$key_rea/", NULL, 'outline-danger', 'fa-flag'); ?>
                                            <?php } ?>

                                        </td>
                                    </tr>
                                    <?php $counter++; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->

<?php SectionManager::start('scripts') ?>
<!-- DataTables JS Plugins -->
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-bs5/js/dataTables.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive-bs5/js/responsive.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/dataTables.buttons.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-bs5/js/buttons.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-jszip/jszip.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-pdfmake/pdfmake.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-pdfmake/vfs_fonts.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/buttons.print.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/buttons.html5.min.js"></script>

<!-- DataTables JS Code -->
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/_js/pages/be_tables_datatables.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/_js/pages/be_comp_dialogs.js"></script>

<?php SectionManager::end('scripts') ?>
