<?php View::content();?>
<h1>Listado de %Model%</h1>
<?= Html::linkAction('add', 'add');?>
<?php if (count($%lcaseModels%) == 0) { ?>
	<strong>No se han encontrado elementos para %Model%</strong>
<?php } ?>
<table>
	<thead>
		%columnListHead%
		<th>Opciones</th>
	</thead>
	<tbody>
	<?php foreach($%lcaseModels% as $fila):?>
		<tr>
			%columnListBody%
			<td>
				<?= Html::linkAction('edit/' . $fila->id,'Editar');?>
				<?= Html::linkAction('delete/' . $fila->id,'Borrar', 'onclick="return confirmar();"');?>
			</td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>

<script type="text/javascript">
	function confirmar()
	{
		return confirm('Desea eliminar este elemento');
	}
</script>
