<?php View::flash(); ?>
<?php SectionManager::start('styles')  ?>
<!-- DataTables CSS -->
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-bs5/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-bs5/css/buttons.bootstrap5.min.css">
<link rel="stylesheet" href="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive-bs5/css/responsive.bootstrap5.min.css">
<!-- END DataTables CSS -->
<?php SectionManager::end('styles')  ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header text-end">
                    <?= DwHtml::button("admin/productos/agregar/", 'Nuevo', null, 'fa-check')  ?>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="tProductos" class="table table-bordered table-vcenter table-hover js-dataTable-full table-striped table-condensed table-responsive">
                            <thead>
                                <tr>
                                    <th class="text-center" width="5%">#</th>
                                    <th class="text-center">codigo</th>
                                    <th class="text-center">nombre</th>
                                    <th class="text-center">categoria</th>
                                    <th class="text-center">unidad</th>
                                    <th class="text-center">existencia</th>
                                    <th class="text-center">costo</th>
                                    <th class="text-center"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $count = 1;
                                ?>
                                <?php foreach ($productos as $producto) { ?>
                                    <?php $key_upd = Security::setKey($producto->id, 'upd_producto'); ?>
                                    <?php $key_del = Security::setKey($producto->id, 'del_producto'); ?>
                                    <?php $key_shw = Security::setKey($producto->id, 'shw_producto'); ?>
                                    <tr>
                                        <td class="text-center">
                                            <?= $count++ ?>
                                        </td>
                                        <td><?= $producto->codigo ?></td>
                                        <td><?= $producto->nombre ?></td>
                                        <td><?= $producto->getCategoria()->nombre ?></td>
                                        <td><?= $producto->getUnidad()->nombre ?></td>
                                        <td class="text-center"><?= $producto->existencia ?></td>
                                        <td class="text-end"><?= $producto->costo ?></td>
                                        <td class="text-center" width="10%" nowrap>
                                            <?= DwHtml::buttonTable('Ver', "admin/productos/ver/$key_shw/", null, 'info', 'fa-eye'); ?>
                                            <?= DwHtml::buttonTable('Editar', "admin/productos/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                            <?= DwHtml::buttonTableSA('Eliminar', "admin/productos/eliminar/$key_del/", array('class' => 'js-confirm', 'msg-nombre' => "$producto->nombre", 'msg-title' => 'Eliminar Registro', 'msg' => '¿Está seguro de eliminar este registro? <br/>¡Recuerda que esta operación no se puede reversar.!'), 'danger', 'fa-trash'); ?>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->

<?php SectionManager::start('scripts')  ?>
<!-- DataTables JS Plugins -->
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-bs5/js/dataTables.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-responsive-bs5/js/responsive.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/dataTables.buttons.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-bs5/js/buttons.bootstrap5.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-jszip/jszip.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-pdfmake/pdfmake.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons-pdfmake/vfs_fonts.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/buttons.print.min.js"></script>
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/js/plugins/datatables-buttons/buttons.html5.min.js"></script>

<!-- DataTables JS Code -->
<script src="<?= PUBLIC_PATH ?>template/coreui/assets/_js/pages/be_tables_datatables.js"></script>

<?php SectionManager::end('scripts')  ?>
