<?php View::flash(); ?>

<?php echo DwForm::open('sistema/login/entrar/', '', ['class' => 'js-validation-signin', 'id' => 'formulario']) ?>
<?php echo DwForm::focus('login'); ?>

<div class="py-3">
    <div class="mb-4">
        <input type="text" class="form-control form-control-alt form-control-lg" id="login" name="login" placeholder="Usuario">
    </div>
    <div class="mb-4">
        <input type="password" class="form-control form-control-alt form-control-lg" id="password" name="password" placeholder="Password">
    </div>
</div>
<div>
    <?php echo DwForm::hidden('mode', null, 'auth'); ?>
</div>

<div>
    <?php echo DwForm::token(); ?>
</div>
<div class="row mb-4">
    <div class="col-md-6 col-xl-5">
        <button type="submit" class="btn w-100 btn-alt-primary">
            <i class="fa fa-fw fa-sign-in-alt me-1 opacity-50"></i> Entrar
        </button>
    </div>
</div>

<?php echo DwForm::close() ?>
