<?php View::flash(); ?>

<script type="text/javascript">
    function onSend() {
        var bValid = true;
        var login = $("#login");
        var pass = $("#password");
        bValid = bValid && checkLength(login, 4, 0, "El usuario");
        if (bValid) {
            removeError(login);
        }
        bValid = bValid && checkLength(pass, 4, 0, "La contraseña");
        if (bValid) {
            removeError(login);
        }
        bValid = bValid && checkRegexp(login, /^([A-ZÑ0-9])+$/i, "El usuario debe tener caracteres alfanuméricos.");
        if (bValid) {
            removeError(login);
        }
        bValid = bValid && checkRegexp(pass, /^([A-ZÑ0-9\.\-\#\?\_])+$/i, "La contraseña debe tener caracteres [A-Z]-[0-9]-[#?.-]");
        if (bValid) {
            removeError(pass);
        }
        return bValid;
    }
</script>


<?php echo DwForm::open('sistema/login/entrar/', '', ['class' => 'no-ajax form-validate', 'id' => 'formulario', 'before-send' => 'onSend();']) ?>
<?php echo DwForm::focus('login'); ?>

<div class="py-3">
    <div class="mb-4">
        <input type="text" class="form-control form-control-alt form-control-lg" id="login" name="login" placeholder="Usuario">
    </div>
    <div class="mb-4">
        <input type="password" class="form-control form-control-alt form-control-lg" id="password" name="password" placeholder="Password">
    </div>
</div>
<div>
    <?php echo DwForm::hidden('mode', null, 'auth'); ?>
</div>

<div>
    <?php echo DwForm::token(); ?>
</div>
<div class="row mb-4">
    <div class="col-md-6 col-xl-5">
        <button type="submit" class="btn w-100 btn-alt-primary">
            <i class="fa fa-fw fa-sign-in-alt me-1 opacity-50"></i> Entrar
        </button>
    </div>
</div>

<?php echo DwForm::close() ?>
