<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block pt-3">
                <div class="block-header pt-3 d-flex justify-content-center">
                    <?php echo DwHtml::button("sistema/configuracion/", 'basic', array('class' => 'mx-1 btn-sm btn-info'), 'fa-asterisk', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/config/", 'config all', array('class' => 'mx-1 btn-sm btn-info'), 'fa-cog', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class' => 'mx-1 btn-sm btn-info'), 'fa-random', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', array('class' => 'mx-1 btn-sm btn-success active'), 'fa-hdd-o', APP_AJAX); ?>
<!-- Botón reset eliminado por seguridad -->
                    <!--<div class="pull-right">
                        <?php //echo DwHtml::button("sistema/configuracion/reset/", 'reset', array('class' => 'mx-1 btn-sm btn-danger js-confirm', 'msg-title' => 'Restaurar archivos de configuración', 'msg' => 'Está seguro de wanting restaurar los archivos de configuración?'), 'fa-warning', APP_AJAX); ?>
                    </div>-->
                </div>
                <div class="block-content">

                    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'no-ajax')); ?>

                    <div class="row justify-content-evenly">

                        <div class="col-md-5">
                            <fieldset class="border px-3">
                                <legend class="float-none w-auto block-header block-header-default">Desarrollo</legend>
                                <?php echo DwForm::text('development.host', array('class' => 'input-lower input-required'), $databases['development']['host'], 'Servidor:'); ?>
                                <?php echo DwForm::text('development.username', array('class' => 'input-lower input-required'), $databases['development']['username'], 'Usuario:'); ?>
                                <?php echo DwForm::text('development.password', array('class' => 'input-lower'), $databases['development']['password'], 'Contraseña:'); ?>
                                <?php echo DwForm::text('development.name', array('class' => 'input-lower input-required'), $databases['development']['name'], 'Base de datos:'); ?>
                                <?php echo DwForm::text('development.type', array('class' => 'input-lower input-required'), $databases['development']['type'], 'Conector:'); ?>
                                <?php echo DwForm::text('development.charset', array('class' => 'input-lower input-required'), $databases['development']['charset'], 'Caracteres:'); ?>
                            </fieldset>
                        </div>

                        <div class="col-md-5">
                            <fieldset class="border px-3">
                                <legend class="float-none w-auto block-header block-header-default">Producción</legend>
                                <?php echo DwForm::text('production.host', array('class' => 'input-lower input-required'), $databases['production']['host'], 'Servidor:'); ?>
                                <?php echo DwForm::text('production.username', array('class' => 'input-lower input-required'), $databases['production']['username'], 'Usuario:'); ?>
                                <?php echo DwForm::text('production.password', array('class' => 'input-lower'), $databases['production']['password'], 'Contraseña:'); ?>
                                <?php echo DwForm::text('production.name', array('class' => 'input-lower input-required'), $databases['production']['name'], 'Base de datos:'); ?>
                                <?php echo DwForm::text('production.type', array('class' => 'input-lower input-required'), $databases['production']['type'], 'Conector:'); ?>
                                <?php echo DwForm::text('production.charset', array('class' => 'input-lower input-required'), $databases['production']['charset'], 'Caracteres:'); ?>
                            </fieldset>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-3 text-end">
                        <div class="form-actions">
                            <?php echo DwForm::send('Guardar configuración'); ?>
                            <?php echo DwForm::cancel(); ?>
                        </div>
                    </div>
                    <?php echo DwForm::close(); ?>
                </div>
            </div>
        </div>
    </div>
</div>