<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block pt-3">
                <div class="block-header pt-3 d-flex justify-content-center">
                    <?php echo DwHtml::button("sistema/configuracion/", 'basic', array('class' => 'mx-1 btn-sm btn-success active'), 'fa-asterisk', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/empresa/", 'empresa', array('class' => 'mx-1 btn-sm btn-info'), 'fa-building', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/config/", 'config all', array('class' => 'mx-1 btn-sm btn-info'), 'fa-asterisk', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class' => 'mx-1 btn-sm btn-info'), 'fa-random', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', array('class' => 'mx-1 btn-sm btn-info'), 'fa-hdd-o', APP_AJAX); ?>
                </div>
                <div class="block-content">

                    <?php echo DwForm::open('', 'post', array('class' => 'no-ajax')); ?>

                    <div class="row justify-content-center">

                        <div class="col-md-6">

                            <fieldset class="border px-3">
                                <legend class="float-none w-auto block-header block-header-default">Configuración básica</legend>
                                <?php echo DwForm::text('application.name', array('class' => 'input-lower input-required'), $config['application']['name'], 'Nombre del proyecto:'); ?>

                                <?php echo DwForm::text('application.base_url', array('class' => 'input-lower input-required'), $config['application']['base_url'], 'Ruta base del proyecto:'); ?>

                                <?php echo DwForm::select('application.production', array('Off' => 'No', 'On' => 'Si'), array('class' => 'input-required'), $config['application']['production'], 'Proyecto en producción:'); ?>

                                <?php echo DwForm::select('application.database', array('development' => 'Development', 'production' => 'Production'), array('class' => 'input-required'), $config['application']['database'], 'Entorno de conexión BD:'); ?>

                                <?php echo DwForm::text('application.dbdate', array('class' => 'input-required input-lower'), $config['application']['dbdate'], 'Formato de fecha en BD:'); ?>

                                <?php echo DwForm::select('application.debug', array('Off' => 'No', 'On' => 'Si'), array('class' => 'input-required'), $config['application']['debug'], 'Muestra errores en pantalla:'); ?>

                                <?php echo DwForm::select('application.log_exceptions', array('Off' => 'No', 'On' => 'Si'), array('class' => 'input-required'), $config['application']['log_exceptions'], 'Muestra las excepciones en pantalla:'); ?>

                                <?php echo DwForm::text('application.template', array('class' => 'input-lower input-required'), $config['application']['template'], 'Plantilla del proyecto:'); ?>

                                <p>Si no existe en el directorio, se usará la plantilla por defecto</p>
                            </fieldset>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-3 text-end">
                        <div class="form-actions">
                            <?php echo DwForm::send('Guardar configuración'); ?>
                            <?php echo DwForm::cancel(); ?>
                        </div>
                    </div>
                    <?php echo DwForm::close(); ?>
                </div>
            </div>
        </div>
    </div>
</div>