<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block pt-3">
                <div class="block-header pt-3 d-flex justify-content-center">
                    <?php echo DwHtml::button("sistema/configuracion/", 'basic', array('class' => 'mx-1 btn-sm btn-info'), 'fa-asterisk', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/empresa/", 'empresa', array('class' => 'mx-1 btn-sm btn-info'), 'fa-building', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/config/", 'config all', array('class' => 'mx-1 btn-sm btn-info'), 'fa-cog', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class' => 'mx-1 btn-sm btn-success active'), 'fa-random', APP_AJAX); ?>
                    <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', array('class' => 'mx-1 btn-sm btn-info'), 'fa-hdd-o', APP_AJAX); ?>
<!-- Botón reset eliminado por seguridad -->
                    <!--<div class="pull-right">
                        <?php //echo DwHtml::button("sistema/configuracion/reset/", 'reset', array('class' => 'mx-1 btn-sm btn-danger js-confirm', 'msg-title' => 'Restaurar archivos de configuración', 'msg' => 'Está seguro de wanting restaurar los archivos de configuración?'), 'fa-warning', APP_AJAX); ?>
                    </div>-->
                </div>
                <div class="block-content">

                    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'no-ajax')); ?>

                    <div class="row justify-content-evenly">

                        <div class="col-md-5">
                            <fieldset class="border px-3">
                                <legend class="float-none w-auto block-header block-header-default">Enrutamiento</legend>
                                <?php if (isset($routes['routes'])): ?>
                                    <?php foreach ($routes['routes'] as $campo => $valor): ?>
                                        <?php if ($campo == '/'): ?>
                                            <?php echo DwForm::text("routes.$campo", array('class' => 'input-lower input-required'), 'principal', $campo, 'Controlador principal'); ?>
                                        <?php elseif ($campo == '/status/'): ?>
                                            <?php echo DwForm::hidden("routes.$campo", null, $valor); ?>
                                        <?php elseif ($campo == '/sistema/instalacion/*' or $campo == '/*'): ?>
                                            <?php echo DwForm::hidden("routes.$campo", null, 'delete-var'); ?>
                                        <?php else: ?>
                                            <?php echo DwForm::text("routes.$campo", array('class' => 'input-lower input-required'), $valor, $campo); ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <div id="append-config"></div>
                                <p>Para anular una regla puede colocar el valor "delete-var" en el input.</p>
                            </fieldset>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-3 text-end">
                        <div class="form-actions">
                            <?php echo DwForm::send('Guardar configuración'); ?>
                            <?php echo DwForm::cancel(); ?>
                        </div>
                    </div>
                    <?php echo DwForm::close(); ?>
                </div>
            </div>
        </div>
    </div>
</div>