<?php View::flash(); ?>

<!-- Page Content -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-content">
                    <fieldset class="border p-2">
                        <legend class="float-none w-auto block-header block-header-default">Datos del unidad</legend>
                        <div class="row text-center">
                            <div class="col-md-4">
                                <label for="" class="control-label mb-2">Nombre:</label>
                                <h5><?= $unidad->nombre ?? ''; ?></h5>
                            </div>
                        </div>

                    </fieldset>
                </div>
                <div class="block-content">
                    <div class="row mb-3 mt-3">
                        <div class="form-actions">
                            <div class="text-left">
                                <?= DwButton::back('administracion/unidades/listar', 'Regresar al listado', 'fa-undo', 'Atras'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->
